# Generated by Django 4.2.7 on 2023-11-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
