# Generated by Django 4.2.7 on 2023-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('sum', models.BigIntegerField()),
                ('transaction_type', models.BooleanField()),
                ('category_id', models.IntegerField(choices=[(0, 'Clothes'), (1, 'Supermarkets'), (2, 'Restaraunts'), (3, 'Service'), (4, 'Financial'), (5, 'Medicine'), (6, 'Salary'), (7, 'Debt'), (8, 'Gift'), (9, 'Fun')], default=8)),
                ('datetime', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
